# 应用基础配置
app:
  debug: false
  host: 0.0.0.0
  port: 8080
  log_level: INFO

# Prometheus配置
prometheus:
  host: prometheus-server:9090
  timeout: 30

# LLM模型配置
llm:
  provider: openai # 可选值: openai, ollama - 设置主要的LLM提供商
  model: Qwen/Qwen3-14B # 使用OpenAI提供商时的模型名称
  task_model: Qwen/Qwen3-14B-Instruct
  temperature: 0.3
  max_tokens: 4096
  request_timeout: 360 # LLM请求超时时间(秒)
  # 备用Ollama模型配置
  ollama_model: qwen2.5:3b # Ollama本地模型名称
  ollama_base_url: http://ollama-service:11434/v1 # Ollama API基础URL

# 测试配置
testing:
  skip_llm_tests: false # 设置为true可跳过依赖LLM的测试

# Kubernetes配置
kubernetes:
  in_cluster: true
  # 生产环境通常不需要config_path
  namespace: default

# 根因分析配置
rca:
  default_time_range: 30
  max_time_range: 1440
  anomaly_threshold: 0.7
  correlation_threshold: 0.75
  default_metrics:
    - container_cpu_usage_seconds_total
    - container_memory_working_set_bytes
    - kube_pod_container_status_restarts_total
    - kube_pod_status_phase
    - node_cpu_seconds_total
    - node_memory_MemFree_bytes
    - kubelet_http_requests_duration_seconds_count
    - kubelet_http_requests_duration_seconds_sum

# 预测配置
prediction:
  # 模型路径配置
  model_base_path: /app/data/models
  model_paths:
    qps:
      model: /app/data/models/qps_prediction_model.pkl
      scaler: /app/data/models/qps_prediction_scaler.pkl
      metadata: /app/data/models/qps_prediction_model_metadata.json
    cpu:
      model: /app/data/models/cpu_prediction_model.pkl
      scaler: /app/data/models/cpu_prediction_scaler.pkl
      metadata: /app/data/models/cpu_prediction_model_metadata.json
    memory:
      model: /app/data/models/memory_prediction_model.pkl
      scaler: /app/data/models/memory_prediction_scaler.pkl
      metadata: /app/data/models/memory_prediction_model_metadata.json
    disk:
      model: /app/data/models/disk_prediction_model.pkl
      scaler: /app/data/models/disk_prediction_scaler.pkl
      metadata: /app/data/models/disk_prediction_model_metadata.json
  max_instances: 20
  min_instances: 1
  prometheus_query: 'rate(nginx_ingress_controller_nginx_process_requests_total{service="ingress-nginx-controller-metrics"}[10m])'

# 通知配置
notification:
  enabled: true

# Tavily搜索配置
tavily:
  max_results: 5

# Redis配置 - 用于向量数据缓存和元数据存储
redis:
  host: localhost
  port: 6379
  db: 0
  password: ""
  connection_timeout: 5
  socket_timeout: 5
  max_connections: 10
  decode_responses: true

# 小助手配置
rag:
  vector_db_path: /app/data/vector_db
  collection_name: aiops-assistant-prod
  knowledge_base_path: /app/data/knowledge_base
  chunk_size: 1000
  chunk_overlap: 200
  top_k: 10  # 生产环境增加更多检索数量
  similarity_threshold: 0.25  # 生产环境降低相似度阈值
  openai_embedding_model: Pro/BAAI/bge-m3
  ollama_embedding_model: nomic-embed-text
  max_context_length: 6000
  temperature: 0.1
  timeout: 360 # 智能助手调用超时时间(秒) - 确保足够时间进行复杂推理
  cache_expiry: 3600 # 缓存过期时间(秒)
  max_docs_per_query: 8 # 每次查询最多处理的文档数
  use_enhanced_retrieval: true # 是否使用增强检索
  use_document_compressor: true # 是否使用文档压缩

# MCP配置
mcp:
  server_url: http://localhost:9000 # MCP服务端地址
  timeout: 30 # 请求超时时间(秒)
  max_retries: 3 # 最大重试次数
  health_check_interval: 30 # 健康检查间隔(秒)
